.base:  &base
    user: root
    port: 22
    sshOptions:
        UserKnownHostsFile: /dev/null
        StrictHostKeyChecking: no

develop:
    hostname: agent-develop.xinglin.ai
    <<: *base
    port: 2222
    stage: develop
    roles:
        - app
        - migrate
        - queen
    deploy_path: /data/wwwroot/agent
    #    branch: master

test:
    hostname: agent-test.xinglin.ai
    <<: *base
    port: 2221
    stage: test
    roles:
        - app
        - migrate
        - queen
    deploy_path: /data/wwwroot/agent
    #    branch: master

web-1:
    hostname: 172.16.2.101
    <<: *base
    stage: production
    roles:
        - app
        - queen
        - migrate
    deploy_path: /data/wwwroot/agent-server
    #    branch: master

web-2:
    hostname: 172.16.2.100
    <<: *base
    stage: production
    roles:
        - app
        - migrate
    deploy_path: /data/wwwroot/agent-server
    #    branch: master

