image: ihipop/deployer-toolkit:php7.1-node8.9-dep6.0_china

variables:
  MYSQL_DATABASE: agent
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: no_password

.cache: &cache
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - vendor/
    - node_modules/
    - public/

stages:
  - lint
  - build
  - deploy

# --------------------------------------------------------------------------------------

lint:
  stage: lint
  script:
    - echo '[php]' >/usr/local/etc/php/php.ini
    - echo 'memory_limit=-1' >>/usr/local/etc/php/php.ini
    - phpcs -n --colors --standard=PSR2 --extensions=php --encoding=utf-8 ./app/

# --------------------------------------------------------------------------------------

build:
  stage: build
  cache:
    <<: *cache
  services:
    - mysql:5.6
  script:
    - git checkout -- . #恢复版本控制中被修改的文件
    - bash .ci/build.sh
  only:
    - develop
    - test
    - master

# --------------------------------------------------------------------------------------

# test:
#   stage: test
#   script:
#     - cp .env.ci .env
#     - phpunit --configuration phpunit.xml --coverage-text  --colors
#   only:
#     - develop
#     - test
#     - master

# --------------------------------------------------------------------------------------

deploy_develop:
  stage: deploy
  cache:
    <<: *cache
  script:
    - rm -f .env
    - export DEPLOY_SSH_KEY=$DEV_SSH_KEY
    - entrypoint.sh dep --file=./.ci/deployer/deploy.php config:hosts develop
    - entrypoint.sh dep --file=./.ci/deployer/deploy.php deploy develop
  environment:
    name: develop
    url: http://agent-develop.xinglin.ai
  only:
    - develop

deploy_test:
  stage: deploy
  cache:
    <<: *cache
  script:
    - rm -f .env
    - export DEPLOY_SSH_KEY=$TEST_SSH_KEY
    - entrypoint.sh dep --file=./.ci/deployer/deploy.php config:hosts test
    - entrypoint.sh dep --file=./.ci/deployer/deploy.php deploy test
  environment:
    name: test
    url: http://agent-test.xinglin.ai
  only:
    - test

deploy_production:
  stage: deploy
  cache:
    <<: *cache
  script:
    - rm -f .env
    - export DEPLOY_SSH_KEY=$PROD_SSH_KEY
    - entrypoint.sh dep --file=./.ci/deployer/deploy.php config:hosts production
    - entrypoint.sh dep --file=./.ci/deployer/deploy.php deploy production
  environment:
    name: production
    url: http://agent.xinglin.ai
  artifacts:
    untracked: true
    when: on_success
    expire_in: 2 day
    paths:
      - ./*
  when: manual
  only:
    - master

# --------------------------------------------------------------------------------------
